graphql-python/graphene-pydantic

- README.md
- graphene_pydantic/converters.py
- graphene_pydantic/registry.py
- graphene_pydantic/types.py
- tests/test_forward_refs.py
Some models reference other models that haven't been defined yet, and some models reference each other -- neither of these was supported. This adds support via a `resolve_placeholders()` method, akin to Pydantic's `update_forward_refs()`.
For instance:
``` python
class NodeModel(BaseModel):
id: int
name: str
labels: 'LabelsModel'
class LabelsModel(BaseModel):
node: NodeModel
labels: typing.List[str]
class Node(PydanticObjectType):
class Meta:
model = NodeModel
class Labels(PydanticObjectType):
class Meta:
model = LabelsModel
Node.resolve_placeholders()  # make the `labels` field work
Labels.resolve_placeholders()  # make the `node` field work
```
> Support forward & circular references

- .gitignore
- README.md
- examples/departments.py
Issues [10](https://github.com/upsidetravel/graphene-pydantic/issues/10) and [11](https://github.com/upsidetravel/graphene-pydantic/issues/11) brought up some funkiness around Union types. This updates the README explaining the caveats and giving workarounds.
> Update README with caveats around Union types

- graphene_pydantic/registry.py
- pyproject.toml
Since we've added a substantial new feature and dropped Pydantic 0.x support, we needed at least a minor release
> Bump to 0.1

- .github/workflows/tests.yaml
- tests/test_forward_refs.py
- tox.ini
See #34 -- it's not immediately clear when running the tests that some features require Python 3.7+. Make this clearer by skipping the tests on those platforms. Also, restore automated tests for Python 3.6 since we advertise support for it.
> Skip ForwardRef tests if <3.7

- graphene_pydantic/converters.py
I noticed the TODO message in [converters.py](https://github.com/graphql-python/graphene-pydantic/blob/5388bcf5bb7cb050c4ffbaffe49bea11c51dc24f/graphene_pydantic/converters.py#L135-L138) for hunting down a better way to access the field's description. I was able to access the description from the ModelField's field_info object.
Now, when descriptions are used in the fields of a pydantic model, they will be passed through to the converted graphene Fields. 
```python
import pydantic
import graphene
class PersonModel(pydantic.BaseModel):
id: uuid.UUID
name: str = pydantic.Field(None, description="First, middle, and last name")
```
> Get pydantic field description from field_info

- examples/departments.py
- graphene_pydantic/converters.py
- poetry.lock
- pyproject.toml
- tests/test_forward_refs.py
- tests/test_graphene.py
- tox.ini
Hey, I just spend some time upgrading to graphene v3, it was surprisingly uncomplicated. Tests are green on my end, so lets see what CI has to say ;) Unfortunately I dont have a project using graphene-pydantic, so I had no chance to test my changes in a realistic environment. This PR will solve #36.
I might messed up the `tox.ini` file in an attempt to add graphene v3 there. (lemme know).
Just for reference: [the graphene v3 update tracking issue](https://github.com/graphql-python/graphene/issues/1127). It was decided in [this comment](https://github.com/graphql-python/graphene/issues/1127#issuecomment-670318972) that all graphene integrations shall be updated to graphene v3 before graphene itself will exit beta. (thats why I updated this package, even though I dont use it).
> Upgrade to graphene v3

- graphene_pydantic/objecttype.py
Copies the Pydantic model docstring to the PydanticObjectType if no docstring is set on PydanticObjectType.  This allows for the docstring to appear in schema generation.
> Copy pydantic model docstring to graphene model

- graphene_pydantic/converters.py
I believe this is a bug. 
Currently, when running `find_graphene_type` with a Pydantic `BaseModel`, it will return `None`, which breaks in graphene/graphql with 
`TypeError: MODEL fields cannot be resolved. Expected Graphene type, but received: None.`
The change proposes returning the `Placeholder` object instead of `None`.  
I chose to recall the function, but we could equally do `return registry.get_type_for_model(type_)`.
> Return registry placeholder for `BaseModel` when resolving type

- .github/workflows/tests.yaml
- .pre-commit-config.yaml
- graphene_pydantic/converters.py
- poetry.lock
- pyproject.toml
- tests/test_converters.py
- tox.ini
Fixes for:
- linting issues
- type checking
- Poetry (and other) dependencies
- expanding test coverage to more recent Pythons, and dropping 3.6
- support for more recent Pydantic, and dropping older versions
> Updates for 0.3.0

- graphene_pydantic/converters.py
- pyproject.toml
- tox.ini
From `graphene 2.*` to `graphene 3.0`, the name of the first argument for `graphene.types.field.Field.__init__` changed from `type` to `type_`, which caused some incompatibility issue.  This PR is to fix the issue to make sure that it can also work well with `graphene.2.*`.
> Make it graphene 2 compatible

- graphene_pydantic/converters.py
- tests/test_converters.py
Fixes #56 
Users should be able to subclass datetimes and still have their datetime converted to the proper Graphene type.
I wanted to apply the `issubclass` logic to all types, but I'm holding off since my main goal is to fix compatibility with date mocking libraries like Freezegun.
I ran `poetry run pytest` locally with all 40 tests passing.
> Support subclasses of datetime, date, time

- graphene_pydantic/converters.py
- tests/test_converters.py
> Fix the Required/NonNull behaviour for Pydantic fields with defaults

- graphene_pydantic/converters.py
This PR fixes #38.
In other words, the same behavior as this working graphene can be made to work for a pydantic model
```python
import graphene
class Model(graphene.ObjectType):
class_ = graphene.String(name='class')
class Query(graphene.ObjectType):
model = graphene.Field(Model)
@staticmethod
def resolve_model(parent, info):
return Model(class_='test')
schema = graphene.Schema(query=Query)
print(schema)
print(schema.execute('{model {class}}'))
```
After this patch, this script works, so perhaps this patch is good. I have not been able to fully verify the other behavior.
```python
import graphene
import pydantic
import graphene_pydantic
class Model(pydantic.BaseModel):
class_: str = pydantic.Field(alias='class')
class GrapheneModel(graphene_pydantic.PydanticObjectType):
class Meta:
model …
```
> Mapping pydantic.Field.alias attr as graphene.Field.name

- pyproject.toml
thanks for maintaining this repository!
I found if I use python 3.11, poetry doesn't install pydantic.
So python cannot found pydantic and any tests should be fail.
```sh
$ poetry run pytest
___________________________________ ERROR collecting tests/test_util.py ____________________________________
ImportError while importing test module '/home/conao/dev/forks/graphene-pydantic/tests/test_util.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../../.asdf/installs/python/3.11.1/lib/python3.11/importlib/__init__.py:126: in import_module
return _bootstrap._gcd_import(name[level:], package, level)
tests/test_util.py:1: in <module>
from graphene_pydantic import util
graphene_pydantic/__init__.py:1: in <module>
from .inputobjecttype import …
```
> Install pydantic for python 3.11

- .github/workflows/tests.yaml
- CONTRIBUTING.md
CI is currently broken. Seeing if upgrading the version of the pre-commit/action is a quick win.
Also, updating the CONTRIBUTING.md guide to use poetry, since that's what's used in this repo for managing dependencies.
NOTE: this solves the problem of pre-commit/action failing, but tests are still failing. We'll fix that in https://github.com/graphql-python/graphene-pydantic/pull/88
> Update pre-commit action, update CONTRIBUTING doc to use poetry

- pyproject.toml
Includes a grab-bag of fixes since v0.3.0, including:
- mark Python 3.11 as supported
- handle subclasses of built-in types
- Graphene 2.x compatibility
- support Default field resolver
- Fixes to tests and switch to `nox` instead of `tox` for tests
> Release v0.4.0

- graphene_pydantic/converters.py
- noxfile.py
- pyproject.toml
Fix the dependency in `pyproject.toml` and add a test parameter for the
Graphene 2.x case.
> compat: Restore Graphene 2 support

- CONTRIBUTING.md
- README.md
- Upside Travel no longer exists, remove the CLA.
- Add instructions to run tests to CONTRIBUTING
- Add instructions to run pre-commit and lints to CONTRIBUTING.
> Remove CLA, update CONTRIBUTING guide with testing and linting instructions

- .gitignore
- examples/departments.py
- pyproject.toml
- tests/test_examples/test_departments.py
- Fix `examples/departments.py` to comply with changes in how Pydantic handles Optional and null fields.
- Add test for this example so we automatically catch regressions in the future.
- Add vim .swp and .swo files to the gitignore.
One thing we missed in the review of the PR to add support for pydantic v2: https://github.com/graphql-python/graphene-pydantic/pull/94, is that the example no longer works and errors out.
This is due to a breaking change in the behavior of Pydantic V2 in regards to optional fields. See this section of the v1 to v2 [migration guide](https://docs.pydantic.dev/latest/migration/#required-optional-and-nullable-fields), and this long github issue for more discussion on their treatment of optional / nullable fields: https://github.com/pydantic/pydantic/issues/1223
> Fix example to work with Pydantic V2, add test for examples

- .github/workflows/tests.yaml
> Update test matrix

- noxfile.py
This also adds an exclusion for more recent versions of Python and older
versions of Pydantic, as those aren't compatible.
> Update tested Pydantic versions
